# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceNameARM'
    method: 'POST'
    urlSuffix: 'POST https://dev.azure.com/srijanijeon0817/Testabg/_apis/wit/workitems/${type}?api-version=6.0'
    waitForCompletion: 'false'
